config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  get 'tags/new'
  get 'tags/index'
  get 'users/new'
  get 'pages/index'
  get 'homes/index'
  get 'menus/index'
  get 'menus/term'
  get 'menus/question'
  get 'menus/registation'
  get 'topics/index'
  get 'topics/new'
  get 'search' => 'homes#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/help'

  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'
  
  resources :users
  resources :posts
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/home.rb
class Home < ApplicationRecord
  
 def self.search(keyword)
  where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
 end

end

app/models/menu.rb
class Topic < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true



  belongs_to :user

  mount_uploader :image, ImageUploader
  
  has_many :favorites
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true
  validates :name,length: {maximum: 15}
  validates :email,presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,length: {minimum: 8, maximum: 32}
  validates :password,format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}

  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :posts
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def index
  
  @title = "バイクを検索する"
 
  @url ="https://maps.googleapis.com/maps/api/js?key="+ENV['GOOGLE_MAP_API']+"&callback=initMap"
  
 
 
   
 
 end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  end
  
  def term
  end
  
  def question
  end
  
  def registation
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: email_params[:email])
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def email_params
    params.require(:session).permit(:email)
  end
  
  def password_params
    params.require(:session).permit(:password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @topics = Topic.all
  end
  
  
  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to root_path, success: "登録が完了しました"
      else
        flash.now[:danger] = "登録に失敗しました"
        
        render :new
      end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="users-new-wrapper">
  <div class="container users-new-container-home">
    <div class="col-md-offset-2 col-md-offset-2 ">
       
<h2><%= @title %></h2>

<div id='map'></div>

<style>
#map{
  height: 500px;
  width: 750px;
}
</style>

<script>
function initMap(){
  let map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: 35.6809591, lng: 139.7673068},
  zoom: 8
  });
}
</script>
<script src=<%= @url %> async defer></script>
</div>
 </div>
</div>

app/views/menu/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-dimgray">a</h1>
    <h2 class="text-dimgray">a</h2>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to '利用規約', term_path, class:"border-bottom: solid 1px black" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to 'よくある質問', question_path,class: "border-bottom: solid 1px black"  %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to '登録情報', registation_path,class: "border-bottom: solid 1px black"  %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to 'ログアウトする', logout_path,class: "border-bottom: solid 1px black"  %>
      </div>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-dimgray">a</h1>
    <h2 class="text-dimgray">a</h2>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to '利用規約', menus_term_path, class:"border-bottom: solid 1px black" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to 'よくある質問', menus_question_path,class: "border-bottom: solid 1px black"  %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to '登録情報', menus_registation_path,class: "border-bottom: solid 1px black"  %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to 'ログアウトする', logout_path,class: "border-bottom: solid 1px black"  %>
      </div>
    </div>
  </div>
</div>

app/views/menus/question.html.erb
<h1>よくある質問</h1>

app/views/menus/registation.html.erb
<h1>登録情報を記載</h1>

app/views/menus/term.html.erb
<h1>利用規約</h1>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class= "row">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :写真を選択 %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :コメントを追加 %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-dimgray">会員登録する</h1>
        <%= form_for @user do |f| %>
        
          <div class="form-group">
            <%= f.label :ニックネーム%>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :メールアドレス %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
           <div class="form-group">
            <%= f.label :パスワード%>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :パスワード確認用%>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録する", class: 'btn-block' %>
        <% end %>
        <div class="text-center">
        <%= link_to 'すでに会員の方はこちら', login_path %>
        </div>
      </div>
    </div>
  </div>
</div>