config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  get 'tags/new'
  get 'tags/index'
  get 'users/new'
  get 'pages/index'
  get 'homes/index'
  get 'menus/index'
  get 'menus/term'
  get 'menus/question'
  get 'menus/registation'
  get 'topics/index'
  get 'topics/new'
  get 'search' => 'homes#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/help'

  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'
  
  resources :users
  resources :posts
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/home.rb
class Home < ApplicationRecord
  
 def self.search(keyword)
  where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
 end

end

app/models/menu.rb
class Topic < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true



  belongs_to :user

  mount_uploader :image, ImageUploader
  
  has_many :favorites
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true
  validates :name,length: {maximum: 15}
  validates :email,presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,length: {minimum: 8, maximum: 32}
  validates :password,format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}

  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :posts
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def index
  
  @title = "バイクを検索する"
 
  @url ="https://maps.googleapis.com/maps/api/js?key="+ENV['GOOGLE_MAP_API']+"&callback=initMap"
  
 
 
   
 
 end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  end
  
  def term
  end
  
  def question
  end
  
  def registation
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentalmc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  　<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
　　<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
　　<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  
  
  </head>
  

  <body>
       <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
　　　
    　　<nav class="nav navbar-default navbar-fixed-top navbar-transparent">
    　  　<div class='container'>
        <% if logged_in? %>
        
          <%= link_to homes_index_path do %>
         　<span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        　<% end %>
        
        <% else %>
        
        <%= link_to root_path do %>
         <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        
        <% end %>
        
 
        <ul class="nav navbar-nav navbar-right">
  
          <% if logged_in? %>
            <li>
              <%= link_to  do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_post_path do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>


　　<div class="box1">
　　 <div class="container-footer">
　　   
　　  <div class='row col-md-4'>
　　  
　　    <%= link_to 'バイクを探す', homes_index_path, class: 'btn-square' %>
　　   
　　  </div> 
　　   
　　  <div class='row col-md-4'>
　　   
　　    <%= link_to '投稿を見る', topics_index_path, class: 'btn-square'  %>
　　 
　　  </div>
　　  
　　  <div class='row col-md-4'>
　　   
　　    <%= link_to 'メニュー', menus_index_path, class: 'btn-square'  %>
　　  
　　  </div>

　　 </div>
　　</div>
　　
　　
　　
　　
    <%= yield %>

    
<script>
   $(function(){
    $(".alert").fadeOut(4000);
   });
</script>
    
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white"><b>Rental.M.C</b></h1>
    <h2 class="text-white">バイクをシェアする</h2>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to 'ログインする', login_path, class: 'btn btn-primary btn-dimgray' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= link_to '会員登録をする', new_user_path,class: 'btn btn-primary btn-dimgray' %>
      </div>
    </div>
  </div>
</div>